# Generated by Django 5.0.7 on 2024-08-04 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_slot_name', models.CharField(max_length=30)),
                ('parking_slot_owner_name', models.CharField(max_length=30)),
                ('house_or_society_name', models.CharField(max_length=30)),
                ('parking_location', models.CharField(max_length=30)),
                ('parking_address', models.CharField(max_length=50)),
                ('parking_google_map_url', models.CharField(max_length=250)),
                ('parking_charge_category', models.CharField(max_length=30)),
                ('parking_charge', models.IntegerField(default=0, max_length=20)),
                ('is_vacant', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_engaged', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
