# Generated by Django 5.0.7 on 2024-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addParkingApp', '0005_alter_addparkingslot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addparkingslot',
            name='parking_google_map_url',
            field=models.URLField(max_length=250),
        ),
    ]
