# Generated by Django 5.0.7 on 2024-08-03 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCaretaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caretaker_mobile_number', models.CharField(max_length=20)),
                ('caretaker_profile_image', models.ImageField(upload_to='caretaker_profile/')),
                ('caretaker_nid_image', models.ImageField(upload_to='caretaker_nid/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('three_wheeler', 'Three Wheeler'), ('motorcycle', 'Motorcycle')], max_length=20)),
                ('driver_phone_number', models.CharField(max_length=20)),
                ('driver_profile_image', models.ImageField(upload_to='driver_profile/')),
                ('driver_license_image', models.ImageField(upload_to='driver_license/')),
                ('driver_car_registration_image', models.ImageField(upload_to='driver_registration/')),
                ('is_driver', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Socity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society_phone', models.CharField(default='0', max_length=20)),
                ('society_email', models.CharField(default='example@example.com', max_length=20)),
                ('society_profile_picture', models.ImageField(upload_to='society_profile_pictures/')),
                ('society_house_name', models.CharField(max_length=20)),
                ('s_address', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_mobile_number', models.CharField(max_length=20)),
                ('owner_email_address', models.CharField(max_length=20)),
                ('owner_profile_image', models.ImageField(upload_to='E:\\Sprofile_pictures')),
                ('owner_society_name', models.CharField(max_length=20)),
                ('owner_address', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
