# Generated by Django 5.0.7 on 2024-08-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registercaretaker',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
