# Generated by Django 5.0.7 on 2024-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_registercaretaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
