# Generated by Django 5.0.7 on 2024-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_alter_societyuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdriver',
            name='is_driver',
            field=models.BooleanField(default=True),
        ),
    ]
