# Generated by Django 5.0.2 on 2024-07-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_societyuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societyuser',
            name='user',
        ),
    ]
