# Generated by Django 5.0.2 on 2024-07-29 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_remove_societyuser_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_mobile_number', models.CharField(max_length=20)),
                ('owner_email_address', models.CharField(max_length=20)),
                ('owner_profile_image', models.ImageField(upload_to='E:\\SmartParking\\media\\profile_pictures')),
                ('owner_society_name', models.CharField(max_length=20)),
                ('owner_address', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
