# Generated by Django 5.0.7 on 2024-07-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_registerdriver_is_driver'),
        ('register', '0007_spaceowner'),
    ]

    operations = [
    ]
